version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mariadb:10.4
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-curupira}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-pr0t3c@0}
            MYSQL_PASSWORD: ${DB_PASSWORD:-pr0t3c@0}
            MYSQL_USER: ${DB_USERNAME:-curupira}
        volumes:
            - ./.docker/mariadb/dbdata:/var/lib/mysql
            - ./BackupBDCurupira-20240621-123001.sql:/docker-entrypoint-initdb.d/BackupBDCurupira-20240621-123001.sql
        ports:
            - "3388:3306"
        networks:
            - laravel

    # wordpress:
    #     depends_on:
    #     - db
    #     image: wordpress:latest
    #     restart: always
    #     # Restart line controls the restart mode, meaning if the container stops running for any reason, it will restart the process immediately.
    #     ports:
    #         - "8000:80"
    #   # The previous line defines the port that the WordPress container will use. After successful installation, the full path will look like this: http://localhost:8000
    #     environment:
    #         WORDPRESS_DB_HOST: db
    #         WORDPRESS_DB_USER: ${DB_DATABASE:-curupira}
    #         WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-pr0t3c@0}
    #         WORDPRESS_DB_NAME: ${DB_USERNAME:-curupira}
    #     volumes:
    #         - wordpress_data:/var/www/html/wordpress
    #     networks:
    #         - laravel

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
